#!/bin/bash

PACKAGES_DIR="packages"
SPLUNK_APP_NAME="newrelic_nrql_command_for_splunk"
SPLUNK_APP_VERSION=`cat ${SPLUNK_APP_NAME}/default/app.conf | grep version | awk -F" = " '{print $2}'`
SPLUNK_APP_TAR=${SPLUNK_APP_NAME}"-"${SPLUNK_APP_VERSION}".tgz"

mkdir -p ${PACKAGES_DIR}
gtar -zcv ${SPLUNK_APP_NAME} > ${PACKAGES_DIR}/${SPLUNK_APP_TAR}